function [fitresult, gof] = createFits(Pop_1, GDP_1, Hos_1, Population, roadlane, water, electricity, pop, bui)
%CREATEFITS(POP_1,GDP_1,HOS_1,POPULATION,ROADLANE,WATER,ELECTRICITY,POP,BUI)
%  Create fits.
%
%  Data for 'GDP_POP' fit:
%      X Input : Pop_1
%      Y Output: GDP_1
%  Data for 'HOS_POP' fit:
%      X Input : Pop_1
%      Y Output: Hos_1
%  Data for 'ROAD_POP' fit:
%      X Input : Population
%      Y Output: roadlane
%  Data for 'Water_POP' fit:
%      X Input : Population
%      Y Output: water
%  Data for 'ELE_POP' fit:
%      X Input : Population
%      Y Output: electricity
%  Data for 'Land_POP' fit:
%      X Input : pop
%      Y Output: bui
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2019 15:43:31

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 6, 1 );
gof = struct( 'sse', cell( 6, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'GDP_POP'.
[xData, yData] = prepareCurveData( Pop_1, GDP_1 );

% Set up fittype and options.
ft = fittype( {'x', '1'}, 'independent', 'x', 'dependent', 'y', 'coefficients', {'a', 'b'} );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'GDP_POP' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'GDP_1 vs. Pop_1', 'GDP_POP', 'Location', 'NorthEast' );
% Label axes
xlabel Pop_1
ylabel GDP_1
grid on

%% Fit: 'HOS_POP'.
[xData, yData] = prepareCurveData( Pop_1, Hos_1 );

% Set up fittype and options.
ft = fittype( {'x', '1'}, 'independent', 'x', 'dependent', 'y', 'coefficients', {'a', 'b'} );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'HOS_POP' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'Hos_1 vs. Pop_1', 'HOS_POP', 'Location', 'NorthEast' );
% Label axes
xlabel Pop_1
ylabel Hos_1
grid on

%% Fit: 'ROAD_POP'.
[xData, yData] = prepareCurveData( Population, roadlane );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [25.3985372182151 0.868083225368842];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ROAD_POP' );
h = plot( fitresult{3}, xData, yData );
legend( h, 'roadlane vs. Population', 'ROAD_POP', 'Location', 'NorthEast' );
% Label axes
xlabel Population
ylabel roadlane
grid on

%% Fit: 'Water_POP'.
[xData, yData] = prepareCurveData( Population, water );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [346.069351685266 0.544736476659283];

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Water_POP' );
h = plot( fitresult{4}, xData, yData );
legend( h, 'water vs. Population', 'Water_POP', 'Location', 'NorthEast' );
% Label axes
xlabel Population
ylabel water
grid on

%% Fit: 'ELE_POP'.
[xData, yData] = prepareCurveData( Population, electricity );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1730.14436322421 0.84762189909276];

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ELE_POP' );
h = plot( fitresult{5}, xData, yData );
legend( h, 'electricity vs. Population', 'ELE_POP', 'Location', 'NorthEast' );
% Label axes
xlabel Population
ylabel electricity
grid on

%% Fit: 'Land_POP'.
[xData, yData] = prepareCurveData( pop, bui );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Land_POP' );
h = plot( fitresult{6}, xData, yData );
legend( h, 'bui vs. pop', 'Land_POP', 'Location', 'NorthEast' );
% Label axes
xlabel pop
ylabel bui
grid on


