function [fitresult, gof] = createFit(pop, fir)
%CREATEFIT(POP,FIR)
%  Create a fit.
%
%  Data for '消防设备与人口数' fit:
%      X Input : pop
%      Y Output: fir
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2019 20:29:53


%% Fit: '消防设备与人口数'.
[xData, yData] = prepareCurveData( pop, fir );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', '消防设备与人口数关系' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'fir vs. pop', '拟合曲线', 'Lower bounds ', 'Upper bounds', 'Location', 'NorthEast' );
% Label axes
xlabel log（population）
ylabel log(firework)
grid on


